ports:
    http: 8081
    debug: 5858

auth:
    jwt_secret: 'supersecret'
    expiration_time: 120

mongo:
    url: 'mongodb://localhost:27017/testDB'
    #url: 'mongodb://localhost:27018/testDB'

facebook:
    clientID: 'clientID'
    clientSecret: 'clientSecret'
    callbackURL: 'http://localhost:8081/auth/facebook/callback'

# none/debug/info
loglevel: info